# Generated by Django 6.1.1 on 2026-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorOfferSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
