# Generated by Django 6.1.1 on 2026-09-20 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='The Monday of the week this comparison counts for.')),
                ('savings_vs_most_expensive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_vs_regular', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='one_weekly_comparison_per_user_and_week')],
            },
        ),
    ]
