# Generated by Django 6.1.1 on 2026-09-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shopping_list', 'Shopping List'), ('preferences', 'Preferences'), ('location', 'Location')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('base', models.JSONField(null=True)),
                ('proposed', models.JSONField()),
                ('diff', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
