"""
Django settings for billiger project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6vo_rd@1a^yu4!p(*+&j($aujc^fc%nsejqg$h6qql$l^lq461'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'mcp_server',  # before oauth2_provider: overrides its consent-screen template
    'oauth2_provider',
    'search',
    'accounts',
    'streaks',
    'assistant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

ROOT_URLCONF = 'billiger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'billiger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Vienna'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Celery
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE

# Weekly refresh of Marktguru offer data (Ticket 09) — every Monday at 03:00,
# off-peak and ahead of the week's price comparisons.
CELERY_BEAT_SCHEDULE = {
    'weekly-offer-refresh': {
        'task': 'search.tasks.refresh_offers',
        'schedule': crontab(day_of_week=1, hour=3, minute=0),
    },
}


# Django REST Framework
# Clients are cross-origin (Next.js on :3000), so the API authenticates with
# a per-account token in the Authorization header rather than session cookies.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Brute-force guard for register/login/google (per client IP).
        'auth': '10/min',
        # Every assistant turn is a paid LLM call (per account).
        'assistant': '30/min',
    },
}


# Google sign-in (Ticket 12): the OAuth client ID whose ID tokens are accepted.
# Empty disables Google login (the endpoint answers 503).
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')


# Built-in assistant (Ticket 14): the Anthropic API key and model behind /api/assistant/chat/.
# Without a key the endpoint answers 503. Fallbacks re-run a request the model's safety
# classifiers declined on a fallback model inside the same call; set to 0 to disable.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
ASSISTANT_MODEL = os.environ.get('ASSISTANT_MODEL', 'claude-opus-5')
ASSISTANT_LLM_FALLBACKS = os.environ.get('ASSISTANT_LLM_FALLBACKS', '1') == '1'


# MCP access for external LLM clients (Ticket 16): Billiger is an OAuth 2.1 authorization server
# and the MCP endpoint (/mcp) its resource server. Every access token must be issued for
# MCP_RESOURCE_URL (RFC 8707); set it to the public URL users enter in Claude/ChatGPT.
MCP_RESOURCE_URL = os.environ.get('MCP_RESOURCE_URL', 'http://localhost:8000/mcp')

# One pre-registered OAuth client per platform, no dynamic registration. Claude's redirect URI is
# fixed; ChatGPT shows its own when the connector is created — the ChatGPT client only exists
# once it is set here.
MCP_CLAUDE_REDIRECT_URI = 'https://claude.ai/api/mcp/auth_callback'
MCP_CHATGPT_REDIRECT_URI = os.environ.get('MCP_CHATGPT_REDIRECT_URI', '')

# Browser origins allowed to call /mcp (the MCP spec's DNS-rebinding guard); calls without an
# Origin header (server-to-server) are not affected.
MCP_ALLOWED_ORIGINS = ['https://claude.ai', 'https://chatgpt.com', 'https://chat.openai.com']

# `issue_mcp_dev_token` (internal testing, no end-user flow) only runs with this set: an explicit
# opt-in, since DEBUG alone is no signal here.
MCP_ALLOW_DEV_TOKENS = os.environ.get('MCP_ALLOW_DEV_TOKENS', '') == '1'

# The consent screen needs a signed-in Django session, separate from the API's token auth.
LOGIN_URL = '/accounts/login/'

OAUTH2_PROVIDER = {
    'SCOPES': {
        'billiger:read': 'Einkaufsliste, Preise, Warenkorb-Vergleich und Ersparnis ansehen',
        'billiger:write': 'Änderungen vorschlagen (übernommen wird erst, wenn du es in Billiger bestätigst)',
    },
    # Least privilege when a client asks for no scope.
    'DEFAULT_SCOPES': ['billiger:read'],
    'PKCE_REQUIRED': True,
    'COMPLIANT_BCP_RFC9700_PKCE_METHOD': True,  # S256 only, no "plain"
    'COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT': True,  # authorization code only
    'COMPLIANT_BCP_RFC9700_PASSWORD_GRANT': True,
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 30 * 24 * 3600,
    'ROTATE_REFRESH_TOKEN': True,
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https'],
    # RFC 9728: the resource identifier clients validate the metadata against.
    'OAUTH2_PROTECTED_RESOURCE_IDENTIFIER': MCP_RESOURCE_URL,
    'OAUTH2_PROTECTED_RESOURCE_NAME': 'Billiger',
    # RFC 8707: a token counts only if it was issued for the MCP endpoint.
    'RESOURCE_SERVER_TOKEN_RESOURCE_VALIDATOR': 'mcp_server.audience.validate_mcp_audience',
}
